// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cert-variants/Accessible.tsx": () => import("../components/mockups/cert-variants/Accessible.tsx"),
  "./components/mockups/cert-variants/Affordance.tsx": () => import("../components/mockups/cert-variants/Affordance.tsx"),
  "./components/mockups/cert-variants/Hierarchy.tsx": () => import("../components/mockups/cert-variants/Hierarchy.tsx")
};
