// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rx-detail/AccessibilityVariant.tsx": () => import("../components/mockups/rx-detail/AccessibilityVariant.tsx"),
  "./components/mockups/rx-detail/AffordanceVariant.tsx": () => import("../components/mockups/rx-detail/AffordanceVariant.tsx"),
  "./components/mockups/rx-detail/HierarchyVariant.tsx": () => import("../components/mockups/rx-detail/HierarchyVariant.tsx")
};
